apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recycling-ingress
  namespace: recycling-app
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: recycling.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
